export type CampaignStatusLike =
  | 'DRAFT'
  | 'ACTIVE'
  | 'SCHEDULED'
  | 'PAUSED'
  | 'COMPLETED'
  | 'ARCHIVED'
  | string

export type SocialPostStatusLike =
  | 'DRAFT'
  | 'APPROVED'
  | 'SCHEDULED'
  | 'PUBLISHED'
  | 'FAILED'
  | string

export type PublishModeLike = 'MANUAL' | 'AUTO' | string | null | undefined

export type CampaignOperatingStage =
  | 'strategy_missing'
  | 'strategy_review_needed'
  | 'content_plan_missing'
  | 'content_review_needed'
  | 'content_approved_not_scheduled'
  | 'scheduled_manual'
  | 'scheduled_auto'
  | 'auto_publish_enabled'
  | 'published_waiting_for_analytics'
  | 'performance_ready'
  | 'learning_review_needed'
  | 'paused_or_archived'

export interface CampaignOperatingInput {
  campaign?: {
    status?: CampaignStatusLike | null
    aiOutput?: unknown
    autopilotEnabled?: boolean | null
    autopilotActivatedAt?: string | Date | null
  } | null
  posts?: Array<{
    status?: SocialPostStatusLike | null
    generationStatus?: string | null
    scheduledAt?: string | Date | null
    approvedAt?: string | Date | null
    publishedAt?: string | Date | null
    manuallyPublishedAt?: string | Date | null
    publishMode?: PublishModeLike
    platformPostId?: string | null
    platformUrl?: string | null
    autoGenerated?: boolean | null
    analyticsData?: unknown
    analyticsFetched?: boolean | null
  }>
  pendingLearningCount?: number
}

export interface CampaignOperatingState {
  stage: CampaignOperatingStage
  stageLabel: string
  stageLabelAr: string
  stageHelper: string
  stageHelperAr: string
  primaryAction: {
    label: string
    labelAr: string
    href: string
  }
  blockers: string[]
  counts: {
    totalPosts: number
    draftPosts: number
    approvedPosts: number
    scheduledPosts: number
    autoScheduledPosts: number
    manualScheduledPosts: number
    publishedPosts: number
    apiPublishedPosts: number
    manualPublishedPosts: number
    analyticsReadyPosts: number
    failedPosts: number
    pendingGenerationPosts: number
  }
  truthFlags: {
    hasStrategy: boolean
    hasContentPlan: boolean
    hasDraftContent: boolean
    hasApprovedContent: boolean
    hasScheduledContent: boolean
    hasAutoScheduledContent: boolean
    hasPublishedContent: boolean
    hasApiPublishedContent: boolean
    hasManualPublishedContent: boolean
    hasAnalyticsData: boolean
    hasPendingLearning: boolean
    workflowEnabled: boolean
    autoPublishEnabled: boolean
  }
}

type StageCopy = Pick<
  CampaignOperatingState,
  'stageLabel' | 'stageLabelAr' | 'stageHelper' | 'stageHelperAr' | 'primaryAction'
>

const STAGE_COPY: Record<CampaignOperatingStage, StageCopy> = {
  strategy_missing: {
    stageLabel: 'Strategy missing',
    stageLabelAr: 'الاستراتيجية غير موجودة',
    stageHelper: 'Create or restore the strategy before planning content.',
    stageHelperAr: 'أنشئ الاستراتيجية أو استعدها قبل تخطيط المحتوى.',
    primaryAction: { label: 'Open Strategy', labelAr: 'افتح الاستراتيجية', href: '/strategy' },
  },
  strategy_review_needed: {
    stageLabel: 'Strategy needs review',
    stageLabelAr: 'الاستراتيجية تحتاج مراجعة',
    stageHelper: 'Review the strategy quality before turning it into a content plan.',
    stageHelperAr: 'راجع جودة الاستراتيجية قبل تحويلها إلى خطة محتوى.',
    primaryAction: { label: 'Review strategy', labelAr: 'راجع الاستراتيجية', href: '#strategy' },
  },
  content_plan_missing: {
    stageLabel: 'Content plan missing',
    stageLabelAr: 'خطة المحتوى غير موجودة',
    stageHelper: 'Build a content plan before review, scheduling, or publishing.',
    stageHelperAr: 'أنشئ خطة محتوى قبل المراجعة أو الجدولة أو النشر.',
    primaryAction: { label: 'Build content plan', labelAr: 'إنشاء خطة المحتوى', href: '#build-content-plan' },
  },
  content_review_needed: {
    stageLabel: 'Draft content needs review',
    stageLabelAr: 'مسودات المحتوى تحتاج مراجعة',
    stageHelper: 'Draft content exists. Review it in Content Hub before scheduling or publishing.',
    stageHelperAr: 'توجد مسودات محتوى. راجعها في Content Hub قبل الجدولة أو النشر.',
    primaryAction: { label: 'Review content plan', labelAr: 'راجع خطة المحتوى', href: '/content-hub' },
  },
  content_approved_not_scheduled: {
    stageLabel: 'Content approved, not scheduled',
    stageLabelAr: 'المحتوى معتمد وغير مجدول',
    stageHelper: 'Approved content is waiting for schedule decisions.',
    stageHelperAr: 'المحتوى المعتمد ينتظر قرارات الجدولة.',
    primaryAction: { label: 'Open Content Hub', labelAr: 'افتح Content Hub', href: '/content-hub' },
  },
  scheduled_manual: {
    stageLabel: 'Scheduled manually',
    stageLabelAr: 'مجدول يدوياً',
    stageHelper: 'Scheduled posts require manual publishing or explicit next action.',
    stageHelperAr: 'المنشورات المجدولة تحتاج نشرًا يدويًا أو خطوة صريحة لاحقة.',
    primaryAction: { label: 'Review schedule', labelAr: 'راجع الجدول', href: '/content-hub' },
  },
  scheduled_auto: {
    stageLabel: 'Auto-scheduled',
    stageLabelAr: 'مجدول تلقائياً',
    stageHelper: 'At least one scheduled post is marked for automatic publishing.',
    stageHelperAr: 'يوجد منشور مجدول واحد على الأقل مضبوط للنشر التلقائي.',
    primaryAction: { label: 'Review queue', labelAr: 'راجع القائمة', href: '#autopilot' },
  },
  auto_publish_enabled: {
    stageLabel: 'Auto-publish enabled',
    stageLabelAr: 'النشر التلقائي مفعّل',
    stageHelper: 'Automatic publishing is enabled only for scheduled posts explicitly marked AUTO.',
    stageHelperAr: 'النشر التلقائي مفعّل فقط للمنشورات المجدولة والمعلّمة صراحةً AUTO.',
    primaryAction: { label: 'Review queue', labelAr: 'راجع القائمة', href: '#autopilot' },
  },
  published_waiting_for_analytics: {
    stageLabel: 'Published, waiting for analytics',
    stageLabelAr: 'منشور وينتظر التحليلات',
    stageHelper: 'Published content exists. Performance appears after analytics are fetched.',
    stageHelperAr: 'يوجد محتوى منشور. يظهر الأداء بعد جلب التحليلات.',
    primaryAction: { label: 'Open Performance', labelAr: 'افتح الأداء', href: '#performance' },
  },
  performance_ready: {
    stageLabel: 'Performance data ready',
    stageLabelAr: 'بيانات الأداء جاهزة',
    stageHelper: 'Published content has analytics data available for review.',
    stageHelperAr: 'المحتوى المنشور لديه بيانات أداء متاحة للمراجعة.',
    primaryAction: { label: 'Review performance', labelAr: 'راجع الأداء', href: '#performance' },
  },
  learning_review_needed: {
    stageLabel: 'Learning suggestions need review',
    stageLabelAr: 'اقتراحات التعلم تحتاج مراجعة',
    stageHelper: 'NEXUS found Brand Brain suggestions. Review them before calling them applied learning.',
    stageHelperAr: 'وجد NEXUS اقتراحات لـ Brand Brain. راجعها قبل اعتبارها تعلماً مطبقاً.',
    primaryAction: { label: 'Review Brand Brain suggestions', labelAr: 'راجع اقتراحات Brand Brain', href: '/brand' },
  },
  paused_or_archived: {
    stageLabel: 'Paused or archived',
    stageLabelAr: 'متوقفة أو مؤرشفة',
    stageHelper: 'This campaign is not in an active operating workflow.',
    stageHelperAr: 'هذه الحملة ليست ضمن مسار تشغيل نشط.',
    primaryAction: { label: 'Review campaign', labelAr: 'راجع الحملة', href: '#campaign' },
  },
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return Boolean(value && typeof value === 'object' && !Array.isArray(value))
}

function hasUsableObject(value: unknown): boolean {
  return isRecord(value) && Object.keys(value).length > 0
}

function hasText(value: unknown): boolean {
  return typeof value === 'string' && value.trim().length > 0
}

function hasUsableArray(value: unknown): boolean {
  return Array.isArray(value) && value.length > 0
}

function hasValidDate(value: string | Date | null | undefined): boolean {
  if (!value) return false
  const date = value instanceof Date ? value : new Date(value)
  return !Number.isNaN(date.getTime())
}

export function hasStrategyEvidence(aiOutput: unknown): boolean {
  if (!isRecord(aiOutput)) return false
  if (hasUsableObject(aiOutput.strategy)) return true

  const directKeys = [
    'contentPillars',
    'keyMessage',
    'coreMessage',
    'primaryOffer',
    'positioning',
    'businessObjective',
    'weeklyPlan',
    'weeklyExecutionPlan',
  ]

  return directKeys.some((key) => {
    const value = aiOutput[key]
    return hasText(value) || hasUsableArray(value) || hasUsableObject(value)
  })
}

function strategyReviewPassed(aiOutput: unknown): boolean {
  if (!isRecord(aiOutput)) return false
  const review = aiOutput.sentinelReview
  return isRecord(review) && review.status === 'passed'
}

export function deriveCampaignOperatingState(input: CampaignOperatingInput): CampaignOperatingState {
  const posts = Array.isArray(input.posts) ? input.posts : []
  const status = String(input.campaign?.status ?? '').toUpperCase()
  const hasStrategy = hasStrategyEvidence(input.campaign?.aiOutput)
  const hasStrategyReview = strategyReviewPassed(input.campaign?.aiOutput)
  const workflowEnabled = Boolean(input.campaign?.autopilotEnabled || input.campaign?.autopilotActivatedAt)
  const pendingLearningCount = Math.max(0, Math.trunc(input.pendingLearningCount ?? 0))

  const counts = {
    totalPosts: posts.length,
    draftPosts: 0,
    approvedPosts: 0,
    scheduledPosts: 0,
    autoScheduledPosts: 0,
    manualScheduledPosts: 0,
    publishedPosts: 0,
    apiPublishedPosts: 0,
    manualPublishedPosts: 0,
    analyticsReadyPosts: 0,
    failedPosts: 0,
    pendingGenerationPosts: 0,
  }

  let malformedScheduledPosts = 0

  for (const post of posts) {
    const postStatus = String(post.status ?? '').toUpperCase()
    const generationStatus = String(post.generationStatus ?? '').toUpperCase()
    const publishMode = String(post.publishMode ?? 'MANUAL').toUpperCase()
    const hasScheduledAt = hasValidDate(post.scheduledAt)
    const hasPublishedAt = hasValidDate(post.publishedAt)
    const hasPlatformRef = Boolean(post.platformPostId || post.platformUrl)
    const hasAnalytics = Boolean(post.analyticsData || post.analyticsFetched)

    if (postStatus === 'DRAFT') counts.draftPosts += 1
    if (postStatus === 'APPROVED') counts.approvedPosts += 1
    if (postStatus === 'FAILED') counts.failedPosts += 1
    if (['PENDING', 'GENERATING', 'AWAITING_UPLOAD'].includes(generationStatus)) {
      counts.pendingGenerationPosts += 1
    }

    if (postStatus === 'SCHEDULED') {
      if (hasScheduledAt) {
        counts.scheduledPosts += 1
        if (publishMode === 'AUTO') counts.autoScheduledPosts += 1
        else counts.manualScheduledPosts += 1
      } else {
        malformedScheduledPosts += 1
      }
    }

    if (postStatus === 'PUBLISHED' && hasPublishedAt) {
      counts.publishedPosts += 1
      if (hasPlatformRef) counts.apiPublishedPosts += 1
      if (hasValidDate(post.manuallyPublishedAt) || !hasPlatformRef) counts.manualPublishedPosts += 1
      if (hasAnalytics) counts.analyticsReadyPosts += 1
    }
  }

  const truthFlags = {
    hasStrategy,
    hasContentPlan: counts.totalPosts > 0,
    hasDraftContent: counts.draftPosts > 0,
    hasApprovedContent: counts.approvedPosts > 0,
    hasScheduledContent: counts.scheduledPosts > 0,
    hasAutoScheduledContent: counts.autoScheduledPosts > 0,
    hasPublishedContent: counts.publishedPosts > 0,
    hasApiPublishedContent: counts.apiPublishedPosts > 0,
    hasManualPublishedContent: counts.manualPublishedPosts > 0,
    hasAnalyticsData: counts.analyticsReadyPosts > 0,
    hasPendingLearning: pendingLearningCount > 0,
    workflowEnabled,
    autoPublishEnabled: counts.autoScheduledPosts > 0,
  }

  const blockers: string[] = []
  if (!hasStrategy) blockers.push('strategy')
  if (counts.totalPosts === 0) blockers.push('content_plan')
  if (counts.draftPosts > 0) blockers.push('content_review')
  if (malformedScheduledPosts > 0) blockers.push('scheduled_time')
  if (counts.publishedPosts > 0 && counts.analyticsReadyPosts === 0) blockers.push('analytics')
  if (pendingLearningCount > 0) blockers.push('learning_review')

  let stage: CampaignOperatingStage
  const pausedOrArchived = status === 'PAUSED' || status === 'ARCHIVED'

  if (truthFlags.hasPendingLearning) {
    stage = 'learning_review_needed'
  } else if (truthFlags.hasAnalyticsData) {
    stage = 'performance_ready'
  } else if (truthFlags.hasPublishedContent) {
    stage = 'published_waiting_for_analytics'
  } else if (truthFlags.autoPublishEnabled && truthFlags.workflowEnabled) {
    stage = 'auto_publish_enabled'
  } else if (truthFlags.hasAutoScheduledContent) {
    stage = 'scheduled_auto'
  } else if (truthFlags.hasScheduledContent) {
    stage = 'scheduled_manual'
  } else if (pausedOrArchived) {
    stage = 'paused_or_archived'
  } else if (!truthFlags.hasStrategy && truthFlags.hasContentPlan) {
    stage = 'content_review_needed'
    blockers.push('strategy_evidence_missing')
  } else if (!truthFlags.hasStrategy) {
    stage = 'strategy_missing'
  } else if (!hasStrategyReview && !truthFlags.hasContentPlan) {
    stage = 'strategy_review_needed'
  } else if (!truthFlags.hasContentPlan) {
    stage = 'content_plan_missing'
  } else if (truthFlags.hasDraftContent) {
    stage = 'content_review_needed'
  } else if (truthFlags.hasApprovedContent) {
    stage = 'content_approved_not_scheduled'
  } else {
    stage = 'strategy_review_needed'
  }

  const copy = STAGE_COPY[stage]
  return {
    stage,
    ...copy,
    blockers: Array.from(new Set(blockers)),
    counts,
    truthFlags,
  }
}
