import type { Prisma } from '@prisma/client'
import { getPlannedPostLimit } from '@/lib/commercialPlans'
import { getUtcMonthlyWindow } from '@/lib/campaignCommercial'

export interface PlannedPostAllowance {
  plan: string
  limit: number
  used: number
  remaining: number
  periodStart: Date
  periodEnd: Date
}

/**
 * Reads the monthly AI-planned-post allowance under an account-level lock.
 * Variant B rows do not consume another planned slot. Replaceable drafts for
 * the current campaign are subtracted so regeneration does not double-charge.
 */
export async function readLockedPlannedPostAllowance(
  tx: Prisma.TransactionClient,
  ownerId: string,
  replaceableCampaignId?: string,
  now = new Date(),
): Promise<PlannedPostAllowance> {
  await tx.$queryRawUnsafe('SELECT pg_advisory_xact_lock(hashtext($1))', `post-limit:${ownerId}`)
  const [user, subscription] = await Promise.all([
    tx.user.findUnique({ where: { id: ownerId }, select: { subscriptionStatus: true, role: true } }),
    tx.subscription.findUnique({
      where: { userId: ownerId },
      select: { plan: true, status: true, currentPeriodStart: true, currentPeriodEnd: true },
    }),
  ])
  const active = subscription?.status === 'ACTIVE'
  const plan = String(active ? subscription.plan : (user?.subscriptionStatus || 'FREE')).toUpperCase()
  const limit = getPlannedPostLimit(plan, user?.role)
  const hasCurrentSubscriptionWindow = Boolean(
    active
    && subscription?.currentPeriodStart
    && subscription?.currentPeriodEnd
    && subscription.currentPeriodStart <= now
    && subscription.currentPeriodEnd > now,
  )
  const { periodStart, periodEnd } = hasCurrentSubscriptionWindow
    ? { periodStart: subscription!.currentPeriodStart!, periodEnd: subscription!.currentPeriodEnd! }
    : getUtcMonthlyWindow(now)
  const baseWhere = {
    workspace: { ownerId },
    autoGenerated: true,
    createdAt: { gte: periodStart, lt: periodEnd },
    OR: [{ variantLabel: null }, { variantLabel: { not: 'B' } }],
  } satisfies Prisma.SocialPostWhereInput
  const [total, replaceable] = await Promise.all([
    tx.socialPost.count({ where: baseWhere }),
    replaceableCampaignId
      ? tx.socialPost.count({
          where: {
            ...baseWhere,
            campaignId: replaceableCampaignId,
            status: 'DRAFT',
            publishedAt: null,
          },
        })
      : Promise.resolve(0),
  ])
  const used = Math.max(0, total - replaceable)
  return { plan, limit, used, remaining: Math.max(0, limit - used), periodStart, periodEnd }
}
