'use client'

import { useEffect, useState, useCallback, useRef, Suspense } from 'react'
import { useRouter, useParams, useSearchParams } from 'next/navigation'
import { Sparkles, X } from 'lucide-react'
import Link from 'next/link'
import { useAuth } from '@/lib/auth-context'
import { useI18n } from '@/lib/i18n-context'
import AppShell from '@/components/AppShell'
import VisualGenerator from '@/components/VisualGenerator'
import SocialPublisher from '@/components/SocialPublisher'
import SocialAnalytics from '@/components/SocialAnalytics'
import AIPresenceBar from '@/components/AIPresenceBar'
import BrandDNABadge, { type BrandDNAData } from '@/components/BrandDNABadge'
import StrategySection from '@/components/StrategySection'
import StrategyActionCard from '@/components/StrategyActionCard'
import CampaignProofOfWork from '@/components/campaign/CampaignProofOfWork'
import { getBrandBrainReadiness } from '@/lib/brandReadiness'
import { getBrandIndicators } from '@/lib/brandIndicators'
import { getAutopilotLockReason } from '@/lib/publishReadiness'
import StrategyBrief from '@/components/StrategyBrief'
import UpgradeModal from '@/components/UpgradeModal'
import { useBillingStatus } from '@/lib/useBillingStatus'
import PlatformNativeCard from '@/components/PlatformNativeCard'