-- Printable HTML is the production export format currently generated by Nexus.
-- PostgreSQL enum additions are idempotent on supported Supabase/Postgres versions.
ALTER TYPE "ExportFormat" ADD VALUE IF NOT EXISTS 'HTML';
