/**
 * GET /api/cron/lifecycle-emails
 * Runs daily at 10:30 UTC.
 *
 * FL2-D: Customer Journey Automation
 * Checks each active user's stage and fires the right email exactly once.
 *
 * Triggers:
 *   - Brand Brain incomplete 24h after signup → sendBrandBrainIncompleteEmail
 *   - Content plan drafted but not approved for 5+ days → sendContentAwaitingApprovalEmail
 *   - User inactive for 7 days → sendReEngagementEmail
 *
 * Guard: each email type can only fire once per user per 14 days.
 * We track this in User.preferences.lifecycleEmailsSent = { [type]: ISO date }
 */

import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import {
  sendBrandBrainIncompleteEmail,
  sendContentAwaitingApprovalEmail,
  sendReEngagementEmail,
} from '@/lib/email/resend'
import { getBrandBrainReadiness } from '@/lib/brandReadiness'
import { cronAuthError } from '@/lib/cronAuth'

export const dynamic = 'force-dynamic'

const COOLDOWN_DAYS = 14  // minimum days between same email type per user

function daysSince(date: Date | string | null | undefined): number {
  if (!date) return 9999
  return Math.floor((Date.now() - new Date(date).getTime()) / (1000 * 60 * 60 * 24))
}

function canSend(prefs: any, key: string): boolean {
  const lastSent = prefs?.lifecycleEmailsSent?.[key]
  if (!lastSent) return true
  return daysSince(lastSent) >= COOLDOWN_DAYS
}

async function markSent(userId: string, prefs: any, key: string) {
  const updated = {
    ...(prefs ?? {}),
    lifecycleEmailsSent: {
      ...(prefs?.lifecycleEmailsSent ?? {}),
      [key]: new Date().toISOString(),
    },
  }
  await prisma.user.update({
    where: { id: userId },
    data: { preferences: updated },
  }).catch(() => null)
}

export async function GET(req: NextRequest) {
  const authError = cronAuthError(req)
  if (authError) return authError

  const results = {
    usersChecked: 0,
    brandBrainEmails: 0,
    approvalNudgeEmails: 0,
    reEngagementEmails: 0,
    errors: [] as string[],
  }

  try {
    // Load users with workspace + brand profile + recent activity
    const users = await prisma.user.findMany({
      where: {
        email: { not: '' },
        createdAt: { lte: new Date(Date.now() - 24 * 60 * 60 * 1000) }, // at least 24h old
      },
      include: {
        workspaces: {
          include: {
            brandProfile: true,
            campaigns: {
              orderBy: { updatedAt: 'desc' },
              take: 5,
              select: {
                id: true,
                name: true,
                updatedAt: true,
              },
            },
          },
          take: 1,
          orderBy: { createdAt: 'desc' },
        },
      },
    })

    results.usersChecked = users.length

    for (const user of users) {
      if (!user.email) continue
      const prefs = user.preferences as any ?? {}
      const ws = user.workspaces[0]
      if (!ws) continue

      // ── Trigger 1: Brand Brain incomplete 24h after signup ─────────────
      if (canSend(prefs, 'brandBrainIncomplete') && daysSince(user.createdAt) >= 1) {
        const brand = ws.brandProfile
        const readiness = brand ? getBrandBrainReadiness(brand as any) : { score: 0, ready: false, missingRequired: [], missingRecommended: [], message: '' }
        if (readiness.score < 60) {
          try {
            await sendBrandBrainIncompleteEmail(user.email, user.name ?? '', readiness.score)
            await markSent(user.id, prefs, 'brandBrainIncomplete')
            results.brandBrainEmails++
          } catch (e: any) {
            results.errors.push(`brandBrain ${user.email}: ${e.message}`)
          }
          continue // one email per user per cron run
        }
      }

      // ── Trigger 2: Content plan awaiting approval 5+ days ──────────────
      if (canSend(prefs, 'approvalNudge')) {
        try {
          // Find campaigns with DRAFT social posts older than 5 days
          const staleCampaign = await (prisma.socialPost as any).findFirst({
            where: {
              workspaceId: ws.id,
              status: 'DRAFT',
              autoGenerated: true,
              createdAt: { lte: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000) },
            },
            select: { campaignId: true, createdAt: true },
            orderBy: { createdAt: 'asc' },
          })

          if (staleCampaign?.campaignId) {
            const [postCount, campaign] = await Promise.all([
              (prisma.socialPost as any).count({
                where: { campaignId: staleCampaign.campaignId, status: 'DRAFT' },
              }),
              prisma.campaign.findUnique({
                where: { id: staleCampaign.campaignId },
                select: { id: true, name: true, createdAt: true },
              }),
            ])

            if (campaign && postCount > 0) {
              const draftDays = daysSince(staleCampaign.createdAt)
              await sendContentAwaitingApprovalEmail(
                user.email,
                user.name ?? '',
                campaign.name,
                postCount,
                draftDays,
                campaign.id,
              )
              await markSent(user.id, prefs, 'approvalNudge')
              results.approvalNudgeEmails++
              continue
            }
          }
        } catch (e: any) {
          results.errors.push(`approvalNudge ${user.email}: ${e.message}`)
        }
      }

      // ── Trigger 3: 7-day inactivity ────────────────────────────────────
      if (canSend(prefs, 'reEngagement')) {
        const lastCampaignActivity = ws.campaigns[0]?.updatedAt
        const lastActive = lastCampaignActivity ?? user.updatedAt
        const idleDays = daysSince(lastActive)

        if (idleDays >= 7) {
          try {
            await sendReEngagementEmail(user.email, user.name ?? '', idleDays)
            await markSent(user.id, prefs, 'reEngagement')
            results.reEngagementEmails++
          } catch (e: any) {
            results.errors.push(`reEngagement ${user.email}: ${e.message}`)
          }
        }
      }
    }
  } catch (err: any) {
    results.errors.push(`Top-level: ${err.message}`)
  }

  return NextResponse.json({ ok: true, ...results, ts: new Date().toISOString() })
}
