/**
 * POST /api/visuals/canvas-upload
 *
 * Accepts a base64 PNG data URL generated by the client-side Canvas API,
 * uploads it to Cloudinary, and returns the permanent CDN URL.
 *
 * Body: { dataUrl: string }
 * Returns: { imageUrl: string }
 */

import { NextRequest, NextResponse } from 'next/server'
import { v2 as cloudinary } from 'cloudinary'
import { getServerUserId } from '@/lib/apiAuth'

if (
  process.env.CLOUDINARY_CLOUD_NAME &&
  process.env.CLOUDINARY_API_KEY &&
  process.env.CLOUDINARY_API_SECRET
) {
  cloudinary.config({
    cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
    api_key:    process.env.CLOUDINARY_API_KEY,
    api_secret: process.env.CLOUDINARY_API_SECRET,
  })
}

export async function POST(req: NextRequest) {
  const userId = await getServerUserId(req)
  if (!userId) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  if (!process.env.CLOUDINARY_CLOUD_NAME) {
    return NextResponse.json({ error: 'Cloudinary not configured' }, { status: 500 })
  }

  try {
    const { dataUrl } = await req.json() as { dataUrl?: string }

    if (!dataUrl || !dataUrl.startsWith('data:image/')) {
      return NextResponse.json({ error: 'Invalid data URL' }, { status: 400 })
    }

    const result = await cloudinary.uploader.upload(dataUrl, {
      folder:        `nexus/post-images/${userId}`,
      resource_type: 'image',
      transformation: [{ quality: 'auto:good' }],
    })

    return NextResponse.json({ imageUrl: result.secure_url })
  } catch (err: unknown) {
    console.error('[canvas-upload]', err)
    const message = err instanceof Error ? err.message : 'Upload failed'
    return NextResponse.json({ error: message }, { status: 500 })
  }
}
