import Link from 'next/link'

export const metadata = { title: 'Privacy Policy | NEXUS AI' }

export default function PrivacyPage() {
  const year = new Date().getFullYear()

  return (
    <div className="min-h-screen bg-gradient-to-br from-dark via-dark-secondary to-dark-tertiary">
      {/* Nav */}
      <nav className="border-b border-dark-tertiary bg-dark/50 backdrop-blur-md sticky top-0 z-40">
        <div className="max-w-7xl mx-auto px-6 py-4 flex justify-between items-center">
          <Link href="/" className="text-2xl font-bold text-accent">NEXUS</Link>
          <Link href="/auth/login" className="text-sm text-gray-400 hover:text-white transition">Sign In →</Link>
        </div>
      </nav>

      <div className="max-w-3xl mx-auto px-6 py-16">
        <h1 className="text-4xl font-bold mb-2">Privacy Policy</h1>
        <p className="text-gray-400 mb-10">Last updated: January 1, {year}</p>

        <div className="space-y-8 text-gray-300 leading-relaxed">
          <section>
            <h2 className="text-xl font-bold text-white mb-3">1. Information We Collect</h2>
            <p>We collect information you provide directly to us, including name, email address, and payment information when you register for an account or subscribe to our services. We also collect information about how you use NEXUS AI, including campaigns created, content generated, and features accessed.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">2. How We Use Your Information</h2>
            <p>We use the information we collect to provide, maintain, and improve our services, process transactions, send you technical notices and support messages, and respond to your comments and questions. We use your campaign data solely to generate AI marketing content on your behalf.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">3. AI-Generated Content</h2>
            <p>Content generated by NEXUS AI on your behalf using the inputs you provide (campaign name, goal, audience, tone) is yours. We do not use your specific campaign inputs to train our AI models. We use anonymized, aggregated usage patterns to improve our service quality.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">4. Data Storage and Security</h2>
            <p>Your data is stored securely using Supabase infrastructure hosted on AWS. We implement industry-standard security measures including encryption in transit and at rest. We retain your data for as long as your account is active or as needed to provide you services.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">5. Sharing of Information</h2>
            <p>We do not sell, trade, or rent your personal information to third parties. We may share your information with trusted service providers who assist us in operating our platform (Supabase, Stripe, OpenAI, Cloudinary, Vercel) under strict confidentiality obligations.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">6. Cookies</h2>
            <p>We use cookies and similar tracking technologies to maintain your session, remember your preferences, and analyze usage patterns. You can control cookies through your browser settings, though disabling cookies may affect functionality.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">7. Your Rights</h2>
            <p>You have the right to access, correct, or delete your personal information at any time through your account settings. You may also request a copy of your data or ask us to restrict its processing by contacting us at the email below.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">8. Contact Us</h2>
            <p>If you have questions about this Privacy Policy, please contact us at <a href="mailto:privacy@nexus-ai.app" className="text-accent hover:text-accent-light transition">privacy@nexus-ai.app</a>.</p>
          </section>
        </div>

        <div className="mt-12 pt-8 border-t border-dark-tertiary flex gap-6 text-sm text-gray-500">
          <Link href="/" className="hover:text-white transition">← Home</Link>
          <Link href="/terms" className="hover:text-white transition">Terms of Service</Link>
        </div>
      </div>
    </div>
  )
}
