import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'
import { prisma } from '@/lib/prisma'

/* ═══════════════════════════════════════════════════════════════════════════
   GET /api/autopilot/queue?campaignId=xxx

   Returns all autopilot-created SocialPost records for a campaign,
   ordered by scheduledAt asc. Used by the Autopilot tab in campaign detail.
   ═══════════════════════════════════════════════════════════════════════════ */

const supabaseAdmin = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

export async function GET(req: NextRequest) {
  try {
    const token = req.headers.get('authorization')?.replace('Bearer ', '')
    if (!token) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    const { data: { user } } = await supabaseAdmin.auth.getUser(token)
    if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    const { searchParams } = new URL(req.url)
    const campaignId = searchParams.get('campaignId')
    if (!campaignId) return NextResponse.json({ error: 'campaignId required' }, { status: 400 })

    const workspace = await prisma.workspace.findFirst({ where: { ownerId: user.id } })
    if (!workspace) return NextResponse.json({ error: 'Workspace not found' }, { status: 404 })

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const posts = await (prisma.socialPost as any).findMany({
      where: { campaignId, workspaceId: workspace.id, autoGenerated: true },
      orderBy: [{ weekNumber: 'asc' }, { scheduledAt: 'asc' }],
    })

    return NextResponse.json({ posts })
  } catch (error) {
    console.error('[Autopilot Queue] Error:', error)
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 })
  }
}

/* DELETE /api/autopilot/queue?campaignId=xxx — pause (cancel all scheduled) */
export async function DELETE(req: NextRequest) {
  try {
    const token = req.headers.get('authorization')?.replace('Bearer ', '')
    if (!token) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    const { data: { user } } = await supabaseAdmin.auth.getUser(token)
    if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    const { searchParams } = new URL(req.url)
    const campaignId = searchParams.get('campaignId')
    if (!campaignId) return NextResponse.json({ error: 'campaignId required' }, { status: 400 })

    const workspace = await prisma.workspace.findFirst({ where: { ownerId: user.id } })
    if (!workspace) return NextResponse.json({ error: 'Workspace not found' }, { status: 404 })

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    await (prisma.socialPost as any).updateMany({
      where: { campaignId, workspaceId: workspace.id, autoGenerated: true, status: 'SCHEDULED' },
      data: { status: 'DRAFT' },
    })

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    await (prisma.campaign as any).update({
      where: { id: campaignId },
      data: { autopilotEnabled: false },
    })

    return NextResponse.json({ ok: true })
  } catch (error) {
    console.error('[Autopilot Pause] Error:', error)
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 })
  }
}
