import { NextRequest, NextResponse } from 'next/server'
import { adminClient } from '@/lib/supabaseAuth'
import { prisma } from '@/lib/prisma'
import { buildLearningEvents } from '@/lib/brandBrainEvents'
import { buildStatusHistory, validateTransition, type StatusHistoryRow } from '@/lib/postStatus'

/* ═══════════════════════════════════════════════════════════════════════════
   GET /api/autopilot/queue?campaignId=xxx

   Returns all autopilot-created SocialPost records for a campaign,
   ordered by scheduledAt asc. Used by the Autopilot tab in campaign detail.
   ═══════════════════════════════════════════════════════════════════════════ */

export async function GET(req: NextRequest) {
  try {
    const token = req.headers.get('authorization')?.replace('Bearer ', '')
    if (!token) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    const { data: { user } } = await adminClient.auth.getUser(token)
    if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    const { searchParams } = new URL(req.url)
    const campaignId = searchParams.get('campaignId')
    if (!campaignId) return NextResponse.json({ error: 'campaignId required' }, { status: 400 })

    const workspace = await prisma.workspace.findFirst({ where: { ownerId: user.id } })
    if (!workspace) return NextResponse.json({ error: 'Workspace not found' }, { status: 404 })

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const posts = await (prisma.socialPost as any).findMany({
      where: { campaignId, workspaceId: workspace.id, autoGenerated: true, publishMode: 'AUTO' },
      orderBy: [{ weekNumber: 'asc' }, { scheduledAt: 'asc' }],
    })

    return NextResponse.json({ posts })
  } catch (error) {
    console.error('[Autopilot Queue] Error:', error)
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 })
  }
}

/* DELETE /api/autopilot/queue?campaignId=xxx — pause (cancel all scheduled) */
export async function DELETE(req: NextRequest) {
  try {
    const token = req.headers.get('authorization')?.replace('Bearer ', '')
    if (!token) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    const { data: { user } } = await adminClient.auth.getUser(token)
    if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    const { searchParams } = new URL(req.url)
    const campaignId = searchParams.get('campaignId')
    if (!campaignId) return NextResponse.json({ error: 'campaignId required' }, { status: 400 })

    const workspace = await prisma.workspace.findFirst({ where: { ownerId: user.id } })
    if (!workspace) return NextResponse.json({ error: 'Workspace not found' }, { status: 404 })

    const campaign = await prisma.campaign.findFirst({
      where: { id: campaignId, workspaceId: workspace.id },
      select: { id: true },
    })
    if (!campaign) return NextResponse.json({ error: 'Campaign not found' }, { status: 404 })

    const scheduledPosts = await (prisma.socialPost as any).findMany({
      where: {
        campaignId,
        workspaceId: workspace.id,
        autoGenerated: true,
        status: 'SCHEDULED',
        publishMode: 'AUTO',
      },
      select: { id: true },
    })

    const history: StatusHistoryRow[] = scheduledPosts
      .filter(() => validateTransition('SCHEDULED', 'APPROVED').ok)
      .map((post: { id: string }) => buildStatusHistory({
        socialPostId: post.id,
        workspaceId: workspace.id,
        fromStatus: 'SCHEDULED',
        toStatus: 'APPROVED',
        actor: 'USER',
        note: 'autopilot paused',
      }))
    const learningEvents = buildLearningEvents(history.map((entry) => ({
      workspaceId: entry.workspaceId,
      campaignId,
      socialPostId: entry.socialPostId,
      from: entry.fromStatus,
      to: entry.toStatus,
      actor: entry.actor,
      publishMode: 'MANUAL',
    })))

    await prisma.$transaction(async (tx) => {
      for (const post of scheduledPosts) {
        await (tx.socialPost as any).updateMany({
          where: { id: post.id, workspaceId: workspace.id, status: 'SCHEDULED' },
          data: {
            status: 'APPROVED',
            scheduledAt: null,
            publishMode: 'MANUAL',
            autoPublishConsentAt: null,
          },
        })
      }
      if (history.length > 0) await (tx.postStatusHistory as any).createMany({ data: history })
      if (learningEvents.length > 0) await (tx.marketingLearningEvent as any).createMany({ data: learningEvents })
      await tx.campaign.updateMany({
        where: { id: campaignId, workspaceId: workspace.id },
        data: { autopilotEnabled: false, autopilotActivatedAt: null },
      })
    })

    return NextResponse.json({ ok: true, unscheduled: scheduledPosts.length })
  } catch (error) {
    console.error('[Autopilot Pause] Error:', error)
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 })
  }
}
