import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { applyBrandOverlayFromProfile, platformToOverlay } from '@/lib/cloudinaryOverlay'
import { generateWithFlux, platformToFluxAspectRatio, platformToOpenAISize } from '@/lib/ai/falGen'
import { buildImagePrompt, type VisualContext } from '@/lib/ai/imageGen'
import { normalizeContentHubImagePromptForPlatform } from '@/lib/contentHubImageFormat'
import {
  checkAndDeductCredits,
  checkDailyImageCap,
  refundCredits,
  refundCreditsForTransaction,
} from '@/lib/credits'
import { cronAuthError } from '@/lib/cronAuth'

export const dynamic = 'force-dynamic'

/* ═══════════════════════════════════════════════════════════════════════════
   GET /api/cron/generate-images

   Vercel Cron Job — runs every 10 minutes and handles one paid image atomically.
   The exact ten-minute cron expression is configured in vercel.json.

   Logic:
   - Find SocialPost records where:
       autoGenerated = true
       status = SCHEDULED
       imagePrompt is set
       imageUrl is null
       scheduledAt is within the next 48 hours
   - One post per run: build a Brand Brain-grounded prompt → generate →
     upload permanently → persist post + audit record in one transaction.
   ═══════════════════════════════════════════════════════════════════════════ */

const CLOUDINARY_CLOUD  = process.env.CLOUDINARY_CLOUD_NAME || process.env.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME
const CLOUDINARY_KEY    = process.env.CLOUDINARY_API_KEY
const CLOUDINARY_SECRET = process.env.CLOUDINARY_API_SECRET
const IMAGE_PROVIDER_TIMEOUT_MS = 35_000
const MEDIA_UPLOAD_TIMEOUT_MS = 10_000

type ImageCreditReservation = {
  userId: string
  creditsUsed: number
  transactionId?: string
  refunded: boolean
}

type PendingImageRefund = {
  id: string
  userId: string
  entityId: string
  entityType: 'social_post_image' | 'generated_visual_image'
}

/**
 * Generate image — auto-detects provider:
 *   FAL_KEY set  → Flux 1.1 Pro Ultra (best photorealism, returns CDN URL)
 *   FAL_KEY unset → gpt-image-1 high quality (returns base64 data URI)
 * Platform-aware sizing applied in both paths.
 */
async function generateImage(
  prompt: string,
  platform: string
): Promise<string> {
  const safePrompt = normalizeContentHubImagePromptForPlatform(prompt, platform)
  // Auto-detect provider — FAL_KEY presence is the only signal
  if (process.env.FAL_KEY) {
    const aspectRatio = platformToFluxAspectRatio(platform)
    console.log(`[Cron generate-images] Using Flux Pro Ultra — aspect ratio: ${aspectRatio}`)
    const result = await generateWithFlux({ prompt: safePrompt, aspectRatio })
    return result.imageUrl // Hosted CDN URL — no base64 needed
  }

  // Fallback: gpt-image-1 high quality
  // Platform-aware sizing — gpt-image-1 supported sizes only
  const size = platformToOpenAISize(platform)

  const res = await fetch('https://api.openai.com/v1/images/generations', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${process.env.OPENAI_API_KEY}`,
    },
    body: JSON.stringify({
      model:   'gpt-image-1',
      prompt: safePrompt,
      n:       1,
      size,
      quality: 'high', // always high — production asset
    }),
    signal: AbortSignal.timeout(IMAGE_PROVIDER_TIMEOUT_MS),
  })

  if (!res.ok) {
    const err = await res.json().catch(() => ({}))
    throw new Error((err as any)?.error?.message || `Image API error: ${res.status}`)
  }

  const data = await res.json()
  // gpt-image-1 returns b64_json (not a URL)
  const b64 = data?.data?.[0]?.b64_json
  if (!b64) throw new Error('Image generation returned no data')

  return `data:image/png;base64,${b64}`
}

async function uploadToCloudinary(imageUrl: string, postId: string): Promise<string> {
  if (!CLOUDINARY_CLOUD || !CLOUDINARY_KEY || !CLOUDINARY_SECRET) {
    throw new Error('Cloudinary not configured')
  }

  const timestamp = Math.round(Date.now() / 1000)
  const publicId = `autopilot/${postId}`
  const sigString = `folder=nexus/autopilot&public_id=${publicId}&timestamp=${timestamp}${CLOUDINARY_SECRET}`

  // SHA-256 via Web Crypto
  const encoder = new TextEncoder()
  const data = encoder.encode(sigString)
  const hashBuffer = await crypto.subtle.digest('SHA-256', data)
  const signature = Array.from(new Uint8Array(hashBuffer)).map(b => b.toString(16).padStart(2, '0')).join('')

  const form = new FormData()
  // gpt-image-1 returns data URIs — Cloudinary accepts them directly as 'file'
  form.append('file', imageUrl)
  form.append('folder', 'nexus/autopilot')
  form.append('public_id', publicId)
  form.append('api_key', CLOUDINARY_KEY)
  form.append('timestamp', String(timestamp))
  form.append('signature', signature)

  const uploadRes = await fetch(`https://api.cloudinary.com/v1_1/${CLOUDINARY_CLOUD}/image/upload`, {
    method: 'POST',
    body: form,
    signal: AbortSignal.timeout(MEDIA_UPLOAD_TIMEOUT_MS),
  })
  const uploadData = await uploadRes.json()
  if (uploadData.error) throw new Error(`Cloudinary: ${uploadData.error.message}`)
  return uploadData.secure_url as string
}

async function refundImageReservation(
  reservation: ImageCreditReservation | undefined,
  reason: string,
): Promise<boolean> {
  if (!reservation || reservation.refunded || reservation.creditsUsed <= 0) return true

  if (reservation.transactionId) {
    const result = await refundCreditsForTransaction({
      userId: reservation.userId,
      transactionId: reservation.transactionId,
      reason,
    })
    if (result && !result.ok) return false
    reservation.refunded = true
    return true
  }

  const result = await refundCredits(reservation.userId, 'IMAGE_GENERATION', reason)
  if (result && !result.ok) return false
  reservation.refunded = true
  return true
}

/**
 * Retry image-credit refunds that failed after a provider/database error.
 * REFUND_PENDING blocks another paid retry for the same post until this exact,
 * idempotent debit is restored. The cron therefore repairs money state even
 * when no image provider is currently configured.
 */
async function reconcilePendingImageRefunds() {
  const pending = await (prisma as any).$queryRawUnsafe(`
    SELECT DISTINCT ON (d."entityType", d."entityId")
      d."id", d."userId", d."entityId", d."entityType"
    FROM "CreditTransaction" d
    LEFT JOIN "SocialPost" p
      ON d."entityType" = 'social_post_image' AND p."id" = d."entityId"
    LEFT JOIN "GeneratedVisual" v
      ON d."entityType" = 'generated_visual_image' AND v."id" = d."entityId"
    WHERE d."action" = 'IMAGE_GENERATION'
      AND d."amount" < 0
      AND (
        (
          d."entityType" = 'social_post_image'
          AND (
            p."generationStatus" = 'REFUND_PENDING'
            OR (p."generationStatus" = 'GENERATING' AND d."createdAt" < now() - interval '5 minutes')
          )
        )
        OR (
          d."entityType" = 'generated_visual_image'
          AND (
            v."status" = 'FAILED'
            OR (v."status" = 'GENERATING' AND d."createdAt" < now() - interval '5 minutes')
          )
        )
      )
      AND NOT EXISTS (
        SELECT 1
        FROM "CreditTransaction" r
        WHERE r."action" = 'REFUND'
          AND r."entityType" = 'credit_transaction'
          AND r."entityId" = d."id"
      )
    ORDER BY d."entityType", d."entityId", d."createdAt" DESC
    LIMIT 20
  `) as PendingImageRefund[]

  let restored = 0
  let stillPending = 0
  for (const debit of pending) {
    const result = await refundCreditsForTransaction({
      userId: debit.userId,
      transactionId: debit.id,
      reason: 'Automatic reconciliation for failed image generation',
    })
    if (!result || result.ok) {
      restored += 1
      if (debit.entityType === 'social_post_image') {
        await prisma.socialPost.updateMany({
          where: { id: debit.entityId, generationStatus: { in: ['REFUND_PENDING', 'GENERATING'] } },
          data: { generationStatus: 'FAILED' },
        })
      } else {
        await (prisma.generatedVisual as any).updateMany({
          where: { id: debit.entityId, status: 'GENERATING' },
          data: {
            status: 'FAILED',
            errorMessage: 'Image generation was interrupted; its credit charge was restored automatically.',
          },
        })
      }
    } else {
      stillPending += 1
    }
  }

  return { checked: pending.length, restored, stillPending }
}

async function buildAutopilotPrompt(post: any): Promise<string> {
  const brand = post.workspace?.brandProfile ?? {}
  const campaign = post.campaignId
    ? await prisma.campaign.findFirst({
      where: { id: post.campaignId, workspaceId: post.workspaceId },
      select: { name: true, goal: true, tone: true, audience: true, aiOutput: true },
    })
    : null
  const aiOutput = campaign?.aiOutput && typeof campaign.aiOutput === 'object'
    ? campaign.aiOutput as Record<string, any>
    : {}
  const strategy = aiOutput.strategy && typeof aiOutput.strategy === 'object'
    ? aiOutput.strategy as Record<string, any>
    : aiOutput
  const postContext = [
    post.caption,
    post.imagePrompt ? `Creative direction: ${post.imagePrompt}` : null,
  ].filter(Boolean).join('\n')

  const context: VisualContext = {
    visualType: 'SOCIAL_PREVIEW',
    visualStyle: 'Premium',
    campaignName: campaign?.name ?? undefined,
    campaignGoal: campaign?.goal ?? undefined,
    campaignTone: campaign?.tone ?? undefined,
    audience: campaign?.audience ?? undefined,
    brandName: brand.brandName ?? undefined,
    brandToneWords: Array.isArray(brand.toneKeywords) ? brand.toneKeywords : [],
    primaryOffer: brand.primaryOffer ?? undefined,
    industry: brand.industry ?? undefined,
    colorPalette: Array.isArray(brand.colorPalette)
      ? brand.colorPalette.join(', ')
      : brand.colorPalette ?? undefined,
    visualStylePref: brand.visualStyle ?? undefined,
    uniqueAdvantages: Array.isArray(brand.uniqueAdvantages)
      ? brand.uniqueAdvantages.slice(0, 4).join(', ')
      : undefined,
    positioning: strategy.positioning ?? undefined,
    visualDirection: strategy.visualDirection ?? undefined,
    differentiation: strategy.differentiation ?? undefined,
    keyMessage: strategy.keyMessage ?? undefined,
    postCaption: postContext,
    platform: post.platform,
    creativeRequirement: {
      objective: campaign?.goal ?? undefined,
      platform: post.platform,
      sourcePreference: 'generated',
      textOverlayNeeded: true,
      logoNeeded: true,
    },
    assetRole: 'post_background',
  }

  const result = await buildImagePrompt(context)
  return normalizeContentHubImagePromptForPlatform(result.prompt, post.platform)
}

export async function GET(req: NextRequest) {
  const authError = cronAuthError(req)
  if (authError) return authError
  const refundReconciliation = await reconcilePendingImageRefunds()
  if (!CLOUDINARY_CLOUD || !CLOUDINARY_KEY || !CLOUDINARY_SECRET) {
    return NextResponse.json({ error: 'Cloudinary not configured', refundReconciliation }, { status: 503 })
  }
  if (!process.env.FAL_KEY && !process.env.OPENAI_API_KEY) {
    return NextResponse.json({ error: 'No image provider configured', refundReconciliation }, { status: 503 })
  }

  const now = new Date()
  const in48h = new Date(now.getTime() + 48 * 60 * 60 * 1000)

  // Find autopilot posts due in the next 48h that still need an image
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const pendingPosts: any[] = await (prisma.socialPost as any).findMany({
    where: {
      autoGenerated: true,
      status: 'SCHEDULED',
      scheduledAt: { lte: in48h, gte: now },
      imagePrompt: { not: null },
      imageUrl: null,
      generationStatus: { in: ['PENDING', 'FAILED'] },
    },
    include: {
      workspace: {
        select: {
          ownerId: true,
          brandProfile: true,
        },
      },
    },
    orderBy: { scheduledAt: 'asc' },
    take: 1, // one paid provider call must finish or refund before the 60s deadline
  })
  const posts = pendingPosts.slice(0, 1)

  console.log(`[Cron generate-images] Found ${posts.length} posts needing images`)

  const results = await Promise.allSettled(
    posts.map(async (post) => {
      let creditReservation: ImageCreditReservation | undefined
      let visualId: string | null = null
      try {
        const platform: string = post.platform || 'META'
        const ownerId: string | undefined = post.workspace?.ownerId

        // ── Credit gate: deduct IMAGE_GENERATION from workspace owner ───────
        // Autopilot images cost the same as manual image generation.
        // If the user is out of credits, skip this image and log the failure.
        if (!ownerId) {
          console.warn(`[Cron generate-images] Skipped post ${post.id} — workspace owner missing`)
          return { postId: post.id, status: 'skipped_missing_owner' }
        }
        const planUser = await prisma.user.findUnique({
          where: { id: ownerId },
          select: { subscriptionStatus: true },
        })
        const imageCap = await checkDailyImageCap(post.workspaceId, planUser?.subscriptionStatus)
        if (!imageCap.allowed || imageCap.remaining === 0) {
          return { postId: post.id, status: 'skipped_daily_cap', remaining: imageCap.remaining }
        }

        // Atomically claim the job before any charge. Concurrent/manual cron
        // invocations may read the same row, but only one can move it to
        // GENERATING and continue to the wallet/provider path.
        const claim = await prisma.socialPost.updateMany({
          where: {
            id: post.id,
            status: 'SCHEDULED',
            imageUrl: null,
            generationStatus: { in: ['PENDING', 'FAILED'] },
          },
          data: { generationStatus: 'GENERATING' },
        })
        if (claim.count !== 1) {
          return { postId: post.id, status: 'skipped_already_claimed' }
        }

        // Prompt preparation happens before charging. If concept extraction
        // degrades, buildImagePrompt returns its deterministic safe fallback.
        const prompt = await buildAutopilotPrompt(post)
        const creditResult = await checkAndDeductCredits(
          ownerId,
          'IMAGE_GENERATION',
          undefined,
          { entityId: post.id, entityType: 'social_post_image' },
        )
        if (!creditResult.ok) {
          console.warn(`[Cron generate-images] Skipped post ${post.id} — user ${ownerId} has insufficient credits (${creditResult.currentCredits} remaining, need ${creditResult.requiredCredits})`)
          await prisma.socialPost.update({
            where: { id: post.id },
            data: { generationStatus: 'PENDING' },
          })
          return { postId: post.id, status: 'skipped_no_credits', creditsRemaining: creditResult.currentCredits }
        }
        creditReservation = {
          userId: ownerId,
          creditsUsed: creditResult.creditsUsed,
          transactionId: creditResult.transactionId,
          refunded: false,
        }
        console.log(`[Cron generate-images] Deducted IMAGE_GENERATION credits from ${ownerId} — ${creditResult.creditsRemaining} remaining`)
        // ────────────────────────────────────────────────────────────────────

        const visual = await prisma.generatedVisual.create({
          data: {
            workspaceId: post.workspaceId,
            campaignId: post.campaignId ?? null,
            visualType: 'SOCIAL_PREVIEW',
            visualStyle: 'Autopilot Content Hub',
            prompt: post.imagePrompt,
            enhancedPrompt: prompt,
            campaignName: null,
            brandName: post.workspace?.brandProfile?.brandName ?? null,
            status: 'GENERATING',
            parentId: `social-post:${post.id}`,
          },
        })
        visualId = visual.id

        // 1. Generate image — auto-routes to Flux Pro Ultra if FAL_KEY set, else gpt-image-1 high
        console.log(`[Cron generate-images] Generating for ${post.id} — platform: ${platform}, provider: ${process.env.FAL_KEY ? 'flux' : 'gpt-image-1'}`)
        const dataUri = await generateImage(prompt, platform)

        // 2. Upload to Cloudinary for permanence (accepts data URI directly)
        let finalUrl = await uploadToCloudinary(dataUri, post.id)

        // 3. Apply brand overlay (Cloudinary URL transformation — zero extra cost)
        const brand = post.workspace?.brandProfile
        if (brand?.brandName && finalUrl.includes('res.cloudinary.com')) {
          const overlayPlatform = platformToOverlay(post.platform || 'META')
          finalUrl = applyBrandOverlayFromProfile(finalUrl, brand, overlayPlatform)
          console.log(`[Cron generate-images] Brand overlay applied for ${brand.brandName} (${post.id})`)
        }

        // 4. Update the post
        await prisma.$transaction(async (tx) => {
          await tx.socialPost.update({
            where: { id: post.id },
            data: {
              imageUrl: finalUrl,
              generationStatus: 'DONE',
              mediaSource: 'GENERATE',
            },
          })
          await tx.generatedVisual.update({
            where: { id: visualId! },
            data: { imageUrl: finalUrl, status: 'COMPLETED' },
          })
        })

        return { postId: post.id, status: 'ok', url: finalUrl }
      } catch (err: any) {
        console.error(`[Cron generate-images] Failed for post ${post.id}:`, err)
        const refunded = await refundImageReservation(creditReservation, err.message ?? 'Cron image generation failed')
        if (visualId) {
          await prisma.generatedVisual.update({
            where: { id: visualId },
            data: { status: 'FAILED', errorMessage: String(err.message ?? 'Cron image generation failed').slice(0, 500) },
          }).catch(() => {})
        }
        await prisma.socialPost.update({
          where: { id: post.id },
          data: { generationStatus: refunded ? 'FAILED' : 'REFUND_PENDING' },
        }).catch(() => {})
        return {
          postId: post.id,
          status: 'failed',
          error: err.message,
          refundStatus: refunded ? 'restored' : 'pending_reconciliation',
        }
      }
    })
  )

  const summary = results.map(r => r.status === 'fulfilled' ? r.value : { status: 'error', error: (r.reason as Error).message })

  return NextResponse.json({
    processed: posts.length,
    results: summary,
    refundReconciliation,
    runAt: now.toISOString(),
  })
}
