import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { applyBrandOverlayFromProfile, platformToOverlay } from '@/lib/cloudinaryOverlay'

export const dynamic = 'force-dynamic'

/* ═══════════════════════════════════════════════════════════════════════════
   GET /api/cron/generate-images

   Vercel Cron Job — runs every hour.
   Configure in vercel.json:
     { "path": "/api/cron/generate-images", "schedule": "0 * * * *" }

   Logic:
   - Find SocialPost records where:
       autoGenerated = true
       status = SCHEDULED
       imagePrompt is set
       imageUrl is null
       scheduledAt is within the next 48 hours
   - For each post: call DALL-E 3 → upload to Cloudinary → update imageUrl
   ═══════════════════════════════════════════════════════════════════════════ */

const CLOUDINARY_CLOUD  = process.env.CLOUDINARY_CLOUD_NAME || process.env.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME
const CLOUDINARY_KEY    = process.env.CLOUDINARY_API_KEY
const CLOUDINARY_SECRET = process.env.CLOUDINARY_API_SECRET

async function generateDalleImage(prompt: string): Promise<string> {
  const res = await fetch('https://api.openai.com/v1/images/generations', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${process.env.OPENAI_API_KEY}`,
    },
    body: JSON.stringify({
      model: 'dall-e-3',
      prompt: prompt.slice(0, 1000),
      n: 1,
      size: '1024x1024',
      quality: 'standard',
    }),
  })
  const data = await res.json()
  if (data.error) throw new Error(`DALL-E: ${data.error.message}`)
  return data.data?.[0]?.url as string
}

async function uploadToCloudinary(imageUrl: string, postId: string): Promise<string> {
  if (!CLOUDINARY_CLOUD || !CLOUDINARY_KEY || !CLOUDINARY_SECRET) {
    throw new Error('Cloudinary not configured')
  }

  const timestamp = Math.round(Date.now() / 1000)
  const publicId = `autopilot/${postId}`
  const sigString = `public_id=${publicId}&timestamp=${timestamp}${CLOUDINARY_SECRET}`

  // SHA-256 via Web Crypto
  const encoder = new TextEncoder()
  const data = encoder.encode(sigString)
  const hashBuffer = await crypto.subtle.digest('SHA-256', data)
  const signature = Array.from(new Uint8Array(hashBuffer)).map(b => b.toString(16).padStart(2, '0')).join('')

  const form = new FormData()
  form.append('file', imageUrl)
  form.append('upload_preset', 'nexus_autopilot')
  form.append('public_id', publicId)
  form.append('api_key', CLOUDINARY_KEY)
  form.append('timestamp', String(timestamp))
  form.append('signature', signature)

  const uploadRes = await fetch(`https://api.cloudinary.com/v1_1/${CLOUDINARY_CLOUD}/image/upload`, {
    method: 'POST',
    body: form,
  })
  const uploadData = await uploadRes.json()
  if (uploadData.error) throw new Error(`Cloudinary: ${uploadData.error.message}`)
  return uploadData.secure_url as string
}

export async function GET(req: NextRequest) {
  // Verify cron secret
  const authHeader = req.headers.get('authorization')
  if (authHeader !== `Bearer ${process.env.CRON_SECRET}` && process.env.NODE_ENV === 'production') {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const now = new Date()
  const in48h = new Date(now.getTime() + 48 * 60 * 60 * 1000)

  // Find autopilot posts due in the next 48h that still need an image
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const posts: any[] = await (prisma.socialPost as any).findMany({
    where: {
      autoGenerated: true,
      status: 'SCHEDULED',
      scheduledAt: { lte: in48h, gte: now },
      imagePrompt: { not: null },
      imageUrl: null,
    },
    include: {
      workspace: {
        include: { brandProfile: true },
      },
    },
    take: 10, // process up to 10 per run to stay within cron timeout
  })

  console.log(`[Cron generate-images] Found ${posts.length} posts needing images`)

  const results = await Promise.allSettled(
    posts.map(async (post) => {
      try {
        const prompt = post.imagePrompt!

        // 1. Generate with DALL-E 3
        const dalleUrl = await generateDalleImage(prompt)

        // 2. Upload to Cloudinary for permanence
        let finalUrl = dalleUrl
        try {
          finalUrl = await uploadToCloudinary(dalleUrl, post.id)
        } catch (uploadErr) {
          console.warn(`[Cron generate-images] Cloudinary upload failed for ${post.id}, using DALL-E URL:`, uploadErr)
          // Fall back to DALL-E URL (expires in ~1h but better than nothing)
          finalUrl = dalleUrl
        }

        // 3. Apply brand overlay (Cloudinary URL transformation — zero extra cost)
        const brand = post.workspace?.brandProfile
        if (brand?.brandName && finalUrl.includes('res.cloudinary.com')) {
          const overlayPlatform = platformToOverlay(post.platform || 'META')
          finalUrl = applyBrandOverlayFromProfile(finalUrl, brand, overlayPlatform)
          console.log(`[Cron generate-images] Brand overlay applied for ${brand.brandName} (${post.id})`)
        }

        // 4. Update the post
        await prisma.socialPost.update({
          where: { id: post.id },
          data: { imageUrl: finalUrl },
        })

        return { postId: post.id, status: 'ok', url: finalUrl }
      } catch (err: any) {
        console.error(`[Cron generate-images] Failed for post ${post.id}:`, err)
        return { postId: post.id, status: 'failed', error: err.message }
      }
    })
  )

  const summary = results.map(r => r.status === 'fulfilled' ? r.value : { status: 'error', error: (r.reason as Error).message })

  return NextResponse.json({
    processed: posts.length,
    results: summary,
    runAt: now.toISOString(),
  })
}
