import { NextRequest, NextResponse } from 'next/server'
import type { Prisma } from '@prisma/client'
import { prisma } from '@/lib/prisma'
import { generateWithFlux, platformToFluxAspectRatio, platformToOpenAISize } from '@/lib/ai/falGen'
import { buildImagePrompt, generateWithDallE, type VisualContext } from '@/lib/ai/imageGen'
import { reviewGeneratedMediaQuality } from '@/lib/ai/generatedMediaQuality'
import { estimateProfessionalImageCostUsd } from '@/lib/ai/providerEconomics'
import { chooseProfessionalImageProvider } from '@/lib/ai/mediaProviderRouter'
import { normalizeContentHubImagePromptForPlatform } from '@/lib/contentHubImageFormat'
import {
  buildPlatformReadyImageUrl,
  resolvePlatformImageFormat,
} from '@/lib/platformImageFormat'
import { verifyPlatformReadyImage } from '@/lib/platformImageDelivery.server'
import {
  checkAndDeductCredits,
  checkDailyImageCap,
  finalizeCreditDeduction,
  refundCreditDeduction,
  refundCreditsForTransaction,
  type CreditDeductionOk,
} from '@/lib/credits'
import { cronAuthError } from '@/lib/cronAuth'
import { getCreditOperationKey } from '@/lib/creditOperationKey.server'

export const dynamic = 'force-dynamic'
export const maxDuration = 300

/* ═══════════════════════════════════════════════════════════════════════════
   GET /api/cron/generate-images

   Vercel Cron Job — runs every 10 minutes and handles one paid image atomically.
   The exact ten-minute cron expression is configured in vercel.json.

   Logic:
   - Find SocialPost records where:
       autoGenerated = true
       status = SCHEDULED
       imagePrompt is set
       imageUrl is null
       scheduledAt is within the next 48 hours
   - One post per run: build a Brand Brain-grounded prompt → generate →
     upload permanently → persist post + audit record in one transaction.
   ═══════════════════════════════════════════════════════════════════════════ */

const CLOUDINARY_CLOUD  = process.env.CLOUDINARY_CLOUD_NAME || process.env.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME
const CLOUDINARY_KEY    = process.env.CLOUDINARY_API_KEY
const CLOUDINARY_SECRET = process.env.CLOUDINARY_API_SECRET
const MEDIA_UPLOAD_TIMEOUT_MS = 10_000

type ImageCreditReservation = {
  userId: string
  deduction: CreditDeductionOk
  refunded: boolean
}

type PendingImageRefund = {
  id: string
  userId: string
  entityId: string
  entityType: 'social_post_image' | 'generated_visual_image'
}

/**
 * Generate a final ad image using the same quality router as Content Hub.
 * GPT Image 2 is primary; Flux is a controlled fallback for non-reference work.
 */
async function generateImage(
  prompt: string,
  platform: string
): Promise<{
  url: string
  provider: 'openai-gpt-image-2' | 'fal-flux'
  size: '1024x1024' | '1024x1536' | '1536x1024'
  fallbackUsed: boolean
}> {
  const safePrompt = normalizeContentHubImagePromptForPlatform(prompt, platform)
  const decision = chooseProfessionalImageProvider({
    purpose: 'final_ad_creative',
    hasReferenceImage: false,
    openAiConfigured: Boolean(process.env.OPENAI_API_KEY),
    falConfigured: Boolean(process.env.FAL_KEY),
  })
  const size = platformToOpenAISize(platform)

  const runFlux = async () => {
    const aspectRatio = platformToFluxAspectRatio(platform)
    console.log(`[Cron generate-images] Using Flux fallback — aspect ratio: ${aspectRatio}`)
    const result = await generateWithFlux({ prompt: safePrompt, aspectRatio })
    return result.imageUrl
  }

  if (decision.provider === 'fal-flux') {
    return { url: await runFlux(), provider: 'fal-flux', size, fallbackUsed: false }
  }

  try {
    console.log(`[Cron generate-images] Using GPT Image 2 — size: ${size}`)
    return { url: await generateWithDallE(safePrompt, size), provider: 'openai-gpt-image-2', size, fallbackUsed: false }
  } catch (error) {
    if (decision.fallback !== 'fal-flux') throw error
    console.warn('[Cron generate-images] GPT Image 2 failed; using controlled Flux fallback')
    return { url: await runFlux(), provider: 'fal-flux', size, fallbackUsed: true }
  }
}

async function uploadToCloudinary(imageUrl: string, postId: string): Promise<string> {
  if (!CLOUDINARY_CLOUD || !CLOUDINARY_KEY || !CLOUDINARY_SECRET) {
    throw new Error('Cloudinary not configured')
  }

  const timestamp = Math.round(Date.now() / 1000)
  const publicId = `autopilot/${postId}`
  const sigString = `folder=nexus/autopilot&public_id=${publicId}&timestamp=${timestamp}${CLOUDINARY_SECRET}`

  // SHA-256 via Web Crypto
  const encoder = new TextEncoder()
  const data = encoder.encode(sigString)
  const hashBuffer = await crypto.subtle.digest('SHA-256', data)
  const signature = Array.from(new Uint8Array(hashBuffer)).map(b => b.toString(16).padStart(2, '0')).join('')

  const form = new FormData()
  // gpt-image-1 returns data URIs — Cloudinary accepts them directly as 'file'
  form.append('file', imageUrl)
  form.append('folder', 'nexus/autopilot')
  form.append('public_id', publicId)
  form.append('api_key', CLOUDINARY_KEY)
  form.append('timestamp', String(timestamp))
  form.append('signature', signature)

  const uploadRes = await fetch(`https://api.cloudinary.com/v1_1/${CLOUDINARY_CLOUD}/image/upload`, {
    method: 'POST',
    body: form,
    signal: AbortSignal.timeout(MEDIA_UPLOAD_TIMEOUT_MS),
  })
  const uploadData = await uploadRes.json()
  if (uploadData.error) throw new Error(`Cloudinary: ${uploadData.error.message}`)
  return uploadData.secure_url as string
}

async function refundImageReservation(
  reservation: ImageCreditReservation | undefined,
  reason: string,
): Promise<boolean> {
  if (!reservation || reservation.refunded) return true
  const result = await refundCreditDeduction({
    userId: reservation.userId,
    action: 'IMAGE_GENERATION',
    deduction: reservation.deduction,
    reason,
  })
  if (result && !result.ok) return false
  reservation.refunded = true
  return true
}

/**
 * Retry image-credit refunds that failed after a provider/database error.
 * REFUND_PENDING blocks another paid retry for the same post until this exact,
 * idempotent debit is restored. The cron therefore repairs money state even
 * when no image provider is currently configured.
 */
async function reconcilePendingImageRefunds() {
  const pending = await (prisma as any).$queryRawUnsafe(`
    SELECT DISTINCT ON (d."entityType", d."entityId")
      d."id", d."userId", d."entityId", d."entityType"
    FROM "CreditTransaction" d
    LEFT JOIN "SocialPost" p
      ON d."entityType" = 'social_post_image' AND p."id" = d."entityId"
    LEFT JOIN "GeneratedVisual" v
      ON d."entityType" = 'generated_visual_image' AND v."id" = d."entityId"
    WHERE d."action" = 'IMAGE_GENERATION'
      AND d."creditCost" > 0
      AND d."status" = 'RESERVED'
      AND (
        (
          d."entityType" = 'social_post_image'
          AND (
            p."generationStatus" = 'REFUND_PENDING'
            OR (p."generationStatus" = 'GENERATING' AND d."createdAt" < now() - interval '5 minutes')
          )
        )
        OR (
          d."entityType" = 'generated_visual_image'
          AND (
            v."status" = 'FAILED'
            OR (v."status" = 'GENERATING' AND d."createdAt" < now() - interval '5 minutes')
          )
        )
      )
      AND NOT EXISTS (
        SELECT 1
        FROM "CreditTransaction" r
        WHERE r."action" = 'REFUND'
          AND r."entityType" = 'credit_transaction'
          AND r."entityId" = d."id"
      )
    ORDER BY d."entityType", d."entityId", d."createdAt" DESC
    LIMIT 20
  `) as PendingImageRefund[]

  let restored = 0
  let stillPending = 0
  for (const debit of pending) {
    const result = await refundCreditsForTransaction({
      userId: debit.userId,
      transactionId: debit.id,
      reason: 'Automatic reconciliation for failed image generation',
    })
    if (!result || result.ok) {
      restored += 1
      if (debit.entityType === 'social_post_image') {
        await prisma.socialPost.updateMany({
          where: { id: debit.entityId, generationStatus: { in: ['REFUND_PENDING', 'GENERATING'] } },
          data: { generationStatus: 'FAILED' },
        })
      } else {
        await (prisma.generatedVisual as any).updateMany({
          where: { id: debit.entityId, status: 'GENERATING' },
          data: {
            status: 'FAILED',
            errorMessage: 'Image generation was interrupted; its credit charge was restored automatically.',
          },
        })
      }
    } else {
      stillPending += 1
    }
  }

  return { checked: pending.length, restored, stillPending }
}

async function buildAutopilotPrompt(post: any): Promise<string> {
  const brand = post.workspace?.brandProfile ?? {}
  const campaign = post.campaignId
    ? await prisma.campaign.findFirst({
      where: { id: post.campaignId, workspaceId: post.workspaceId },
      select: { name: true, goal: true, tone: true, audience: true, aiOutput: true },
    })
    : null
  const aiOutput = campaign?.aiOutput && typeof campaign.aiOutput === 'object'
    ? campaign.aiOutput as Record<string, any>
    : {}
  const strategy = aiOutput.strategy && typeof aiOutput.strategy === 'object'
    ? aiOutput.strategy as Record<string, any>
    : aiOutput
  const postContext = [
    post.caption,
    post.imagePrompt ? `Creative direction: ${post.imagePrompt}` : null,
  ].filter(Boolean).join('\n')

  const context: VisualContext = {
    visualType: 'SOCIAL_PREVIEW',
    visualStyle: 'Premium',
    campaignName: campaign?.name ?? undefined,
    campaignGoal: campaign?.goal ?? undefined,
    campaignTone: campaign?.tone ?? undefined,
    audience: campaign?.audience ?? undefined,
    brandName: brand.brandName ?? undefined,
    brandToneWords: Array.isArray(brand.toneKeywords) ? brand.toneKeywords : [],
    primaryOffer: brand.primaryOffer ?? undefined,
    industry: brand.industry ?? undefined,
    colorPalette: Array.isArray(brand.colorPalette)
      ? brand.colorPalette.join(', ')
      : brand.colorPalette ?? undefined,
    visualStylePref: brand.visualStyle ?? undefined,
    uniqueAdvantages: Array.isArray(brand.uniqueAdvantages)
      ? brand.uniqueAdvantages.slice(0, 4).join(', ')
      : undefined,
    positioning: strategy.positioning ?? undefined,
    visualDirection: strategy.visualDirection ?? undefined,
    differentiation: strategy.differentiation ?? undefined,
    keyMessage: strategy.keyMessage ?? undefined,
    postCaption: postContext,
    platform: post.platform,
    creativeRequirement: {
      objective: campaign?.goal ?? undefined,
      platform: post.platform,
      sourcePreference: 'generated',
      textOverlayNeeded: true,
      logoNeeded: true,
    },
    assetRole: 'post_background',
  }

  const result = await buildImagePrompt(context)
  return normalizeContentHubImagePromptForPlatform(result.prompt, post.platform)
}

export async function GET(req: NextRequest) {
  const authError = cronAuthError(req)
  if (authError) return authError
  const refundReconciliation = await reconcilePendingImageRefunds()
  if (!CLOUDINARY_CLOUD || !CLOUDINARY_KEY || !CLOUDINARY_SECRET) {
    return NextResponse.json({ error: 'Cloudinary not configured', refundReconciliation }, { status: 503 })
  }
  if (!process.env.FAL_KEY && !process.env.OPENAI_API_KEY) {
    return NextResponse.json({ error: 'No image provider configured', refundReconciliation }, { status: 503 })
  }

  const now = new Date()
  const in48h = new Date(now.getTime() + 48 * 60 * 60 * 1000)

  // Find autopilot posts due in the next 48h that still need an image
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const pendingPosts: any[] = await (prisma.socialPost as any).findMany({
    where: {
      autoGenerated: true,
      status: 'SCHEDULED',
      scheduledAt: { lte: in48h, gte: now },
      imagePrompt: { not: null },
      imageUrl: null,
      generationStatus: { in: ['PENDING', 'FAILED'] },
    },
    include: {
      workspace: {
        select: {
          ownerId: true,
          brandProfile: true,
        },
      },
    },
    orderBy: { scheduledAt: 'asc' },
    take: 1, // one paid provider call must finish or refund before the 60s deadline
  })
  const posts = pendingPosts.slice(0, 1)

  console.log(`[Cron generate-images] Found ${posts.length} posts needing images`)

  const results = await Promise.allSettled(
    posts.map(async (post) => {
      let creditReservation: ImageCreditReservation | undefined
      let visualId: string | null = null
      try {
        const platform: string = post.publishTarget || post.platform || 'META'
        const targetFormat = resolvePlatformImageFormat(platform)
        const ownerId: string | undefined = post.workspace?.ownerId

        // ── Credit gate: deduct IMAGE_GENERATION from workspace owner ───────
        // Autopilot images cost the same as manual image generation.
        // If the user is out of credits, skip this image and log the failure.
        if (!ownerId) {
          console.warn(`[Cron generate-images] Skipped post ${post.id} — workspace owner missing`)
          return { postId: post.id, status: 'skipped_missing_owner' }
        }
        const planUser = await prisma.user.findUnique({
          where: { id: ownerId },
          select: { subscriptionStatus: true },
        })
        const imageCap = await checkDailyImageCap(post.workspaceId, planUser?.subscriptionStatus)
        if (!imageCap.allowed || imageCap.remaining === 0) {
          return { postId: post.id, status: 'skipped_daily_cap', remaining: imageCap.remaining }
        }

        // Atomically claim the job before any charge. Concurrent/manual cron
        // invocations may read the same row, but only one can move it to
        // GENERATING and continue to the wallet/provider path.
        const claim = await prisma.socialPost.updateMany({
          where: {
            id: post.id,
            status: 'SCHEDULED',
            imageUrl: null,
            generationStatus: { in: ['PENDING', 'FAILED'] },
          },
          data: { generationStatus: 'GENERATING' },
        })
        if (claim.count !== 1) {
          return { postId: post.id, status: 'skipped_already_claimed' }
        }

        // Prompt preparation happens before charging. If concept extraction
        // degrades, buildImagePrompt returns its deterministic safe fallback.
        const prompt = await buildAutopilotPrompt(post)
        const creditResult = await checkAndDeductCredits(
          ownerId,
          'IMAGE_GENERATION',
          undefined,
          {
            entityId: post.id,
            entityType: 'social_post_image',
            operationKey: getCreditOperationKey(req, 'IMAGE_GENERATION', 'social_post_image', post.id),
          },
        )
        if (!creditResult.ok) {
          const replay = creditResult.error === 'CREDIT_OPERATION_REPLAY'
          console.warn(replay
            ? `[Cron generate-images] Skipped duplicate operation for post ${post.id} — no additional credits reserved`
            : `[Cron generate-images] Skipped post ${post.id} — user ${ownerId} has insufficient credits (${creditResult.currentCredits} remaining, need ${creditResult.requiredCredits})`)
          await prisma.socialPost.update({
            where: { id: post.id },
            data: { generationStatus: 'PENDING' },
          })
          return {
            postId: post.id,
            status: replay ? 'skipped_duplicate' : 'skipped_no_credits',
            creditsRemaining: replay ? undefined : creditResult.currentCredits,
          }
        }
        creditReservation = {
          userId: ownerId,
          deduction: creditResult,
          refunded: false,
        }
        console.log(`[Cron generate-images] Deducted IMAGE_GENERATION credits from ${ownerId} — ${creditResult.creditsRemaining} remaining`)
        // ────────────────────────────────────────────────────────────────────

        const visual = await prisma.generatedVisual.create({
          data: {
            workspaceId: post.workspaceId,
            campaignId: post.campaignId ?? null,
            visualType: 'SOCIAL_PREVIEW',
            visualStyle: 'Autopilot Content Hub',
            prompt: post.imagePrompt,
            enhancedPrompt: prompt,
            campaignName: null,
            brandName: post.workspace?.brandProfile?.brandName ?? null,
            status: 'GENERATING',
            parentId: `social-post:${post.id}`,
          },
        })
        visualId = visual.id

        // 1. Generate a final creative through the shared professional router.
        console.log(`[Cron generate-images] Generating final creative for ${post.id} — platform: ${platform}`)
        const generatedImage = await generateImage(prompt, platform)
        const dataUri = generatedImage.url

        // 2. Upload to Cloudinary for permanence (accepts data URI directly)
        const durableRawUrl = await uploadToCloudinary(dataUri, post.id)
        const finalUrl = buildPlatformReadyImageUrl(durableRawUrl, targetFormat)

        // 3. Verify the exact platform canvas and visible marketing quality.
        // Copy/logo remain editable; cron must never burn unreviewed raster text.
        const formatValidation = await verifyPlatformReadyImage(finalUrl, targetFormat)
        const qualityReview = await reviewGeneratedMediaQuality({
          mediaType: 'IMAGE',
          outputFrames: [finalUrl],
          campaignMessage: post.caption,
          creativeDirection: post.imagePrompt,
          targetFormat,
          formatValidation,
        })
        if (!qualityReview.passed) {
          await prisma.generatedVisual.update({
            where: { id: visualId },
            data: {
              status: 'FAILED',
              imageUrl: finalUrl,
              errorMessage: 'NEXUS quality review rejected this platform-ready image.',
              qualityStatus: 'REJECTED',
              qualityReview: qualityReview as unknown as Prisma.InputJsonValue,
            },
          })
          throw new Error('NEXUS quality review rejected this platform-ready image')
        }

        // 4. Update the post
        await prisma.$transaction(async (tx) => {
          await tx.socialPost.update({
            where: { id: post.id },
            data: {
              imageUrl: finalUrl,
              generationStatus: 'DONE',
              mediaSource: 'GENERATE',
            },
          })
          await tx.generatedVisual.update({
            where: { id: visualId! },
            data: {
              imageUrl: finalUrl,
              status: 'COMPLETED',
              qualityStatus: 'PASSED',
              qualityReview: qualityReview as unknown as Prisma.InputJsonValue,
            },
          })
        })

        const providerEconomics = estimateProfessionalImageCostUsd({
          provider: generatedImage.provider,
          size: generatedImage.size,
          model: process.env.OPENAI_IMAGE_MODEL || 'gpt-image-2',
          qualityReviewCostUsd: qualityReview.providerUsage?.estimatedProviderCostUsd,
        })
        const finalization = await finalizeCreditDeduction({
          userId: ownerId,
          action: 'IMAGE_GENERATION',
          deduction: creditResult,
          providerEconomics: {
            ...providerEconomics,
            providerUsage: {
              ...providerEconomics.providerUsage,
              qualityReview: qualityReview.providerUsage ?? null,
              fallbackUsed: generatedImage.fallbackUsed,
            },
          },
        })
        if (!finalization.ok) {
          creditReservation.refunded = true
          return {
            postId: post.id,
            status: 'saved_credit_refunded',
            url: finalUrl,
            refundStatus: finalization.refundStatus,
          }
        }

        return { postId: post.id, status: 'ok', url: finalUrl }
      } catch (err: any) {
        console.error(`[Cron generate-images] Failed for post ${post.id}:`, err)
        const publicMessage = 'NEXUS Image Studio could not create a usable image.'
        const refunded = await refundImageReservation(creditReservation, publicMessage)
        if (visualId) {
          await prisma.generatedVisual.update({
            where: { id: visualId },
            data: { status: 'FAILED', errorMessage: publicMessage },
          }).catch(() => {})
        }
        await prisma.socialPost.update({
          where: { id: post.id },
          data: { generationStatus: refunded ? 'FAILED' : 'REFUND_PENDING' },
        }).catch(() => {})
        return {
          postId: post.id,
          status: 'failed',
          error: publicMessage,
          refundStatus: refunded ? 'restored' : 'pending_reconciliation',
        }
      }
    })
  )

  const summary = results.map(r => r.status === 'fulfilled' ? r.value : { status: 'error', error: (r.reason as Error).message })

  return NextResponse.json({
    processed: posts.length,
    results: summary,
    refundReconciliation,
    runAt: now.toISOString(),
  })
}
