import { describe, expect, it, vi } from 'vitest'
import { readLockedPlannedPostAllowance, readPlannedPostAllowance } from '@/lib/postCommercial'

describe('planned-post commercial allowance', () => {
  it('does not count B variants and subtracts replaceable campaign drafts', async () => {
    const tx = {
      $executeRawUnsafe: vi.fn().mockResolvedValue(1),
      user: { findUnique: vi.fn().mockResolvedValue({ subscriptionStatus: 'PRO', role: 'USER' }) },
      subscription: { findUnique: vi.fn().mockResolvedValue(null) },
      socialPost: { count: vi.fn().mockResolvedValueOnce(20).mockResolvedValueOnce(4) },
    } as any

    const allowance = await readLockedPlannedPostAllowance(tx, 'u1', 'campaign-1', new Date('2026-07-12T12:00:00.000Z'))
    expect(allowance).toMatchObject({ plan: 'PRO', limit: 16, used: 16, remaining: 0 })
    expect(tx.socialPost.count).toHaveBeenNthCalledWith(1, {
      where: expect.objectContaining({
        workspace: { ownerId: 'u1' },
        autoGenerated: true,
        OR: [{ variantLabel: null }, { variantLabel: { not: 'B' } }],
      }),
    })
    expect(tx.socialPost.count).toHaveBeenNthCalledWith(2, {
      where: expect.objectContaining({ campaignId: 'campaign-1', status: 'DRAFT', publishedAt: null }),
    })
  })

  it('supports a read-only operational allowance without taking the generation lock', async () => {
    const tx = {
      user: { findUnique: vi.fn().mockResolvedValue({ subscriptionStatus: 'PRO', role: 'USER' }) },
      subscription: { findUnique: vi.fn().mockResolvedValue(null) },
      socialPost: { count: vi.fn().mockResolvedValue(12) },
    } as any

    const allowance = await readPlannedPostAllowance(tx, 'u1', undefined, new Date('2026-07-21T12:00:00.000Z'))

    expect(allowance).toMatchObject({ plan: 'PRO', limit: 16, used: 12, remaining: 4 })
    expect(allowance.periodEnd.toISOString()).toBe('2026-08-01T00:00:00.000Z')
  })
})
